course_name = "优化算法"
course_code = "MATH4002"
notices = ""

[[lecturers]]
name = "孙李刚"

[[lecturers]]
name = "凌超"

[[lecturers]]
name = "孙瑶"

[[textbooks]]
title = "工程最优化设计"
book_author = "李元科"
publisher = "清华大学出版社"
edition = "第二版"
type = "textbook"
author = { name = "", link = "", date = "" }

[[online_resources]]
title = "Convex Optimization – Boyd and Vandenberghe"
url = "https://web.stanford.edu/~boyd/cvxbook/"
description = "推荐阅读。中译：凸优化 (王书宁、许鋆等译)"
author = { name = "", link = "", date = "" }

course = []

[[exam]]
content = "可以携带一张 A4 纸。"
author = { name = "", link = "", date = "" }

lab = []
advice = []
schedule = []
related_links = []
misc = []