course_name = "优化算法"
repo_type = "normal"
course_code = "MATH4002"

description = ""

[[lecturers]]
name = "孙李刚"

[[lecturers]]
name = "凌超"

[[lecturers]]
name = "孙瑶"


[[sections]]
title = "教材"

[[sections.items]]
content = """
- **工程最优化设计**（李元科 / 清华大学出版社 / 第二版 / textbook）
- **Convex Optimization**（Boyd and Vandenberghe / textbook）
- **凸优化**（王书宁、许鋆 等译 / textbook）
"""

[[sections]]
title = "在线资源"

[[sections.items]]
content = "- [Convex Optimization 书籍主页](https://web.stanford.edu/~boyd/cvxbook/)：Boyd and Vandenberghe 著，英文原版资源"

[[sections]]
title = "关于考试"

[[sections.items]]
content = """
可以携带一张 A4 纸。

达到考试要求用《工程最优化设计》这本书足矣。如果对优化有进一步要求，推荐阅读 Boyd 的《Convex Optimization》。
"""
